version: '3.7'
services:
  influxdb:
    image: influxdb
    ports:
    - 8086:8086
  chronograf:
    image: chronograf
    ports:
    - 8888:8888
    command: ["chronograf", "--influxdb-url=http://${INFLUXDB_HOST}:8086"]
  kapacitor:
    image: kapacitor
    environment:
    - KAPACITOR_INFLUXDB_0_URLS_0=http://${INFLUXDB_HOST}:8086
    ports:
    - 9092:9092
